name: research
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: research
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.60.1'
        extended: true

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build Research Website
      env:
        USER: ${{ secrets.SERVER_USER }}
        TARGET: ${{ secrets.SERVER_PATH }}
        KEY: ${{ secrets.SERVER_KEY }}
        DOMAIN: ${{ secrets.SERVER_DOMAIN }}
      run: |
        make
        mkdir ~/.ssh
        echo "$KEY" | tr -d '\r' > ~/.ssh/idkey
        chmod 400 ~/.ssh/idkey
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/idkey
        ssh-keyscan -H $DOMAIN >> ~/.ssh/known_hosts
        rsync -va public/* $USER@$DOMAIN:$TARGET